// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlL6zcxhYjjRnYlxgl9yjMb380nnV41bw',
    appId: '1:688748832044:web:7d231bd0f712c32731f889',
    messagingSenderId: '688748832044',
    projectId: 'organic-plate',
    authDomain: 'organic-plate.firebaseapp.com',
    storageBucket: 'organic-plate.appspot.com',
    measurementId: 'G-VREJ69ZJXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxkBaCr8oSKTz0a9PiEgD02NCu6ZyVV5I',
    appId: '1:688748832044:android:3da8283fd12ef12d31f889',
    messagingSenderId: '688748832044',
    projectId: 'organic-plate',
    storageBucket: 'organic-plate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUqxqYy2UcNQKPKPxaaPiArvn7LwSMmAc',
    appId: '1:688748832044:ios:0f4fd31b21566be031f889',
    messagingSenderId: '688748832044',
    projectId: 'organic-plate',
    storageBucket: 'organic-plate.appspot.com',
    iosBundleId: 'com.example.organicPlate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUqxqYy2UcNQKPKPxaaPiArvn7LwSMmAc',
    appId: '1:688748832044:ios:01631db1c0f91ded31f889',
    messagingSenderId: '688748832044',
    projectId: 'organic-plate',
    storageBucket: 'organic-plate.appspot.com',
    iosBundleId: 'com.example.organicPlate.RunnerTests',
  );
}
